security:
  oauth2:
    client:
      access-token-uri: http://127.0.0.1:8181/oauth/token
      user-authorization-uri: http://127.0.0.1:8181/oauth/authorize
      client-id: Web
    resource:
      user-info-uri: http://127.0.0.1:8181/users/user
      prefer-token-info: false
