server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka8761.com:8761/eureka/
logging:
  path: ./log/discovery-service-8761
